/**
 * AI-Powered Workflow Templates
 * 
 * Pre-built workflow templates that leverage AI, analytics, and customer journey features.
 * These templates demonstrate best practices and common use cases.
 */

export const aiPoweredWorkflowTemplates = [
  {
    id: 'intelligent-ticket-routing',
    name: 'Intelligent Ticket Routing',
    description: 'AI-powered ticket routing based on sentiment, urgency, and customer segment',
    category: 'support',
    tags: ['ai', 'routing', 'tickets', 'sentiment'],
    icon: 'bot',
    nodes: [
      {
        id: 'start-1',
        type: 'start',
        kind: 'start',
        position: { x: 100, y: 200 },
        config: {},
        data: {
          label: 'New Ticket',
          description: 'Triggered when a new ticket is created',
        },
      },
      {
        id: 'ai-analyze-1',
        type: 'ai_decision',
        kind: 'ai_decision',
        position: { x: 300, y: 200 },
        config: {
          content: '{{ticketSubject}}\n\n{{ticketDescription}}',
          analysisTypes: ['intent_classification', 'sentiment_analysis', 'urgency_detection'],
          defaultOutput: 'neutral',
        },
        data: {
          label: 'AI Analysis',
          description: 'Analyze ticket with AI',
          outputs: ['urgent_negative', 'urgent', 'negative', 'positive', 'neutral'],
        },
      },
      {
        id: 'segment-check-1',
        type: 'segment_check',
        kind: 'segment_check',
        position: { x: 550, y: 100 },
        config: {
          segmentNames: ['VIP', 'Enterprise'],
        },
        data: {
          label: 'Check VIP Status',
          description: 'Is customer VIP or Enterprise?',
          outputs: ['in_segment', 'not_in_segment'],
        },
      },
      {
        id: 'assign-priority-1',
        type: 'update_ticket',
        kind: 'update_ticket',
        position: { x: 800, y: 50 },
        config: {
          priority: 'high',
          tags: ['vip', 'urgent'],
        },
        data: {
          label: 'Set High Priority',
          description: 'VIP + Urgent = High Priority',
        },
      },
      {
        id: 'assign-normal-1',
        type: 'update_ticket',
        kind: 'update_ticket',
        position: { x: 800, y: 150 },
        config: {
          priority: 'medium',
        },
        data: {
          label: 'Set Medium Priority',
          description: 'Urgent but not VIP',
        },
      },
      {
        id: 'assign-low-1',
        type: 'update_ticket',
        kind: 'update_ticket',
        position: { x: 800, y: 300 },
        config: {
          priority: 'low',
        },
        data: {
          label: 'Set Low Priority',
          description: 'Not urgent',
        },
      },
      {
        id: 'assign-agent-1',
        type: 'assign_ticket',
        kind: 'assign_ticket',
        position: { x: 1050, y: 150 },
        config: {
          autoAssign: true,
        },
        data: {
          label: 'Auto-assign to Agent',
          description: 'Smart agent assignment',
        },
      },
      {
        id: 'track-1',
        type: 'track_event',
        kind: 'track_event',
        position: { x: 1300, y: 150 },
        config: {
          eventType: 'ticket.routed',
          data: {
            sentiment: '{{aiAnalysis.sentiment}}',
            urgency: '{{aiAnalysis.urgency}}',
            isVIP: '{{inSegment}}',
          },
        },
        data: {
          label: 'Track Routing',
          description: 'Log analytics event',
        },
      },
      {
        id: 'end-1',
        type: 'end',
        kind: 'end',
        position: { x: 1550, y: 150 },
        config: {},
        data: {
          label: 'Complete',
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'start-1', target: 'ai-analyze-1' },
      { id: 'e2', source: 'ai-analyze-1', target: 'segment-check-1', sourceHandle: 'urgent_negative' },
      { id: 'e3', source: 'ai-analyze-1', target: 'segment-check-1', sourceHandle: 'urgent' },
      { id: 'e4', source: 'ai-analyze-1', target: 'assign-low-1', sourceHandle: 'positive' },
      { id: 'e5', source: 'ai-analyze-1', target: 'assign-low-1', sourceHandle: 'neutral' },
      { id: 'e6', source: 'segment-check-1', target: 'assign-priority-1', sourceHandle: 'in_segment' },
      { id: 'e7', source: 'segment-check-1', target: 'assign-normal-1', sourceHandle: 'not_in_segment' },
      { id: 'e8', source: 'assign-priority-1', target: 'assign-agent-1' },
      { id: 'e9', source: 'assign-normal-1', target: 'assign-agent-1' },
      { id: 'e10', source: 'assign-low-1', target: 'assign-agent-1' },
      { id: 'e11', source: 'assign-agent-1', target: 'track-1' },
      { id: 'e12', source: 'track-1', target: 'end-1' },
    ],
  },

  {
    id: 'churn-prevention-flow',
    name: 'Proactive Churn Prevention',
    description: 'Automatically detect at-risk customers and trigger retention campaigns',
    category: 'retention',
    tags: ['churn', 'retention', 'ai', 'campaigns'],
    icon: 'alert-triangle',
    nodes: [
      {
        id: 'start-1',
        type: 'start',
        kind: 'start',
        position: { x: 100, y: 200 },
        config: { trigger: 'scheduled', schedule: 'daily' },
        data: { label: 'Daily Churn Check', description: 'Runs daily' },
      },
      {
        id: 'churn-1',
        type: 'churn_risk_check',
        kind: 'churn_risk_check',
        position: { x: 350, y: 200 },
        config: { autoCreateCampaign: true },
        data: {
          label: 'Check Churn Risk',
          description: 'AI-powered churn assessment',
          outputs: ['low', 'medium', 'high', 'critical'],
        },
      },
      {
        id: 'journey-1',
        type: 'journey_checkpoint',
        kind: 'journey_checkpoint',
        position: { x: 600, y: 100 },
        config: { getRecommendations: true, stageName: 'At Risk' },
        data: { label: 'Track Journey', description: 'Get recommendations' },
      },
      {
        id: 'notify-csm-1',
        type: 'send-notification',
        kind: 'send-notification',
        position: { x: 850, y: 50 },
        config: {
          to: 'csm@company.com',
          subject: 'High Churn Risk Alert: {{customerName}}',
          content: 'Customer {{customerName}} has high churn risk ({{churnProbability}}%). Interventions: {{interventions}}',
        },
        data: { label: 'Alert CSM', description: 'Notify customer success' },
      },
      {
        id: 'send-offer-1',
        type: 'template-message',
        kind: 'send_message',
        position: { x: 850, y: 150 },
        config: {
          channel: 'email',
          template: 'retention_offer',
          templateParams: { customerName: '{{customerName}}', offer: 'special_discount' },
        },
        data: { label: 'Send Retention Offer', description: 'Email special offer' },
      },
      {
        id: 'track-1',
        type: 'track_event',
        kind: 'track_event',
        position: { x: 1100, y: 100 },
        config: {
          eventType: 'churn.intervention',
          data: {
            riskLevel: '{{churnRisk}}',
            probability: '{{churnProbability}}',
            campaignCreated: '{{campaignCreated}}',
          },
        },
        data: { label: 'Log Intervention', description: 'Track analytics' },
      },
      {
        id: 'end-1',
        type: 'end',
        kind: 'end',
        position: { x: 1350, y: 150 },
        config: {},
        data: { label: 'Complete' },
      },
      {
        id: 'end-2',
        type: 'end',
        kind: 'end',
        position: { x: 600, y: 300 },
        config: {},
        data: { label: 'Low Risk - Skip' },
      },
    ],
    edges: [
      { id: 'e1', source: 'start-1', target: 'churn-1' },
      { id: 'e2', source: 'churn-1', target: 'journey-1', sourceHandle: 'high' },
      { id: 'e3', source: 'churn-1', target: 'journey-1', sourceHandle: 'critical' },
      { id: 'e4', source: 'churn-1', target: 'end-2', sourceHandle: 'low' },
      { id: 'e5', source: 'churn-1', target: 'end-2', sourceHandle: 'medium' },
      { id: 'e6', source: 'journey-1', target: 'notify-csm-1' },
      { id: 'e7', source: 'journey-1', target: 'send-offer-1' },
      { id: 'e8', source: 'notify-csm-1', target: 'track-1' },
      { id: 'e9', source: 'send-offer-1', target: 'track-1' },
      { id: 'e10', source: 'track-1', target: 'end-1' },
    ],
  },

  {
    id: 'personalized-onboarding',
    name: 'Personalized Customer Onboarding',
    description: 'Journey-driven onboarding with segment-based personalization',
    category: 'onboarding',
    tags: ['onboarding', 'journey', 'segmentation', 'personalization'],
    icon: 'map-pin',
    nodes: [
      {
        id: 'start-1',
        type: 'start',
        kind: 'start',
        position: { x: 100, y: 200 },
        config: { trigger: 'customer.created' },
        data: { label: 'New Customer', description: 'Triggered on signup' },
      },
      {
        id: 'segment-1',
        type: 'segment_check',
        kind: 'segment_check',
        position: { x: 300, y: 200 },
        config: { segmentNames: ['Enterprise', 'SMB', 'Startup'] },
        data: {
          label: 'Identify Segment',
          description: 'Check customer segment',
          outputs: ['in_segment', 'not_in_segment'],
        },
      },
      {
        id: 'journey-1',
        type: 'journey_checkpoint',
        kind: 'journey_checkpoint',
        position: { x: 500, y: 200 },
        config: { stageName: 'Onboarding Started', getRecommendations: true },
        data: { label: 'Start Journey', description: 'Track onboarding start' },
      },
      {
        id: 'send-enterprise-1',
        type: 'template-message',
        kind: 'send_message',
        position: { x: 700, y: 100 },
        config: {
          channel: 'email',
          template: 'onboarding_enterprise',
          templateParams: { customerName: '{{customerName}}', accountManager: '{{accountManager}}' },
        },
        data: { label: 'Enterprise Welcome', description: 'Dedicated onboarding' },
      },
      {
        id: 'send-smb-1',
        type: 'template-message',
        kind: 'send_message',
        position: { x: 700, y: 200 },
        config: {
          channel: 'email',
          template: 'onboarding_smb',
          templateParams: { customerName: '{{customerName}}', resources: 'quick_start_guide' },
        },
        data: { label: 'SMB Welcome', description: 'Self-service onboarding' },
      },
      {
        id: 'send-default-1',
        type: 'template-message',
        kind: 'send_message',
        position: { x: 700, y: 300 },
        config: {
          channel: 'email',
          template: 'onboarding_default',
          templateParams: { customerName: '{{customerName}}' },
        },
        data: { label: 'Standard Welcome', description: 'Generic onboarding' },
      },
      {
        id: 'track-1',
        type: 'track_event',
        kind: 'track_event',
        position: { x: 950, y: 200 },
        config: {
          eventType: 'customer.onboarding.started',
          data: { segment: '{{segmentNames}}', journeyStage: '{{journeyStage}}' },
        },
        data: { label: 'Track Start', description: 'Log onboarding event' },
      },
      {
        id: 'delay-1',
        type: 'delay',
        kind: 'delay',
        position: { x: 1150, y: 200 },
        config: { duration: 86400000 },
        data: { label: 'Wait 24h', description: 'Day 1 follow-up' },
      },
      {
        id: 'journey-2',
        type: 'journey_checkpoint',
        kind: 'journey_checkpoint',
        position: { x: 1350, y: 200 },
        config: { stageName: 'Day 1 Check-in', getRecommendations: true },
        data: { label: 'Day 1 Milestone', description: 'Track progress' },
      },
      {
        id: 'end-1',
        type: 'end',
        kind: 'end',
        position: { x: 1550, y: 200 },
        config: {},
        data: { label: 'Complete' },
      },
    ],
    edges: [
      { id: 'e1', source: 'start-1', target: 'segment-1' },
      { id: 'e2', source: 'segment-1', target: 'journey-1' },
      { id: 'e3', source: 'journey-1', target: 'send-enterprise-1', condition: 'segmentNames contains Enterprise' },
      { id: 'e4', source: 'journey-1', target: 'send-smb-1', condition: 'segmentNames contains SMB' },
      { id: 'e5', source: 'journey-1', target: 'send-default-1', condition: 'default' },
      { id: 'e6', source: 'send-enterprise-1', target: 'track-1' },
      { id: 'e7', source: 'send-smb-1', target: 'track-1' },
      { id: 'e8', source: 'send-default-1', target: 'track-1' },
      { id: 'e9', source: 'track-1', target: 'delay-1' },
      { id: 'e10', source: 'delay-1', target: 'journey-2' },
      { id: 'e11', source: 'journey-2', target: 'end-1' },
    ],
  },

  {
    id: 'sentiment-based-escalation',
    name: 'Sentiment-Based Ticket Escalation',
    description: 'Automatically escalate tickets with negative sentiment and high urgency',
    category: 'support',
    tags: ['ai', 'sentiment', 'escalation', 'tickets'],
    icon: 'trending-up',
    nodes: [
      {
        id: 'start-1',
        type: 'start',
        kind: 'start',
        position: { x: 100, y: 200 },
        config: { trigger: 'message.received' },
        data: { label: 'New Message', description: 'Customer reply received' },
      },
      {
        id: 'ai-1',
        type: 'ai_decision',
        kind: 'ai_decision',
        position: { x: 300, y: 200 },
        config: {
          content: '{{messageContent}}',
          analysisTypes: ['sentiment_analysis', 'urgency_detection', 'escalation_prediction'],
          defaultOutput: 'neutral',
        },
        data: {
          label: 'Analyze Sentiment',
          description: 'AI sentiment analysis',
          outputs: ['urgent_negative', 'urgent', 'negative', 'neutral', 'positive'],
        },
      },
      {
        id: 'escalate-1',
        type: 'escalate_ticket',
        kind: 'escalate_ticket',
        position: { x: 550, y: 100 },
        config: { level: 2, reason: 'Negative sentiment detected' },
        data: { label: 'Escalate to L2', description: 'High priority escalation' },
      },
      {
        id: 'notify-1',
        type: 'send-notification',
        kind: 'send-notification',
        position: { x: 800, y: 100 },
        config: {
          to: 'manager@company.com',
          subject: 'Urgent Escalation: Ticket {{ticketId}}',
          content: 'Negative sentiment detected. Customer: {{customerName}}. Sentiment: {{aiAnalysis.sentiment}}',
        },
        data: { label: 'Notify Manager', description: 'Alert management' },
      },
      {
        id: 'track-escalation-1',
        type: 'track_event',
        kind: 'track_event',
        position: { x: 1050, y: 100 },
        config: {
          eventType: 'ticket.escalated',
          data: { sentiment: '{{aiAnalysis.sentiment}}', urgency: '{{aiAnalysis.urgency}}', reason: 'ai_sentiment' },
        },
        data: { label: 'Log Escalation', description: 'Track analytics' },
      },
      {
        id: 'end-escalated-1',
        type: 'end',
        kind: 'end',
        position: { x: 1300, y: 100 },
        config: {},
        data: { label: 'Escalated' },
      },
      {
        id: 'end-normal-1',
        type: 'end',
        kind: 'end',
        position: { x: 550, y: 300 },
        config: {},
        data: { label: 'Normal Flow' },
      },
    ],
    edges: [
      { id: 'e1', source: 'start-1', target: 'ai-1' },
      { id: 'e2', source: 'ai-1', target: 'escalate-1', sourceHandle: 'urgent_negative' },
      { id: 'e3', source: 'ai-1', target: 'end-normal-1', sourceHandle: 'neutral' },
      { id: 'e4', source: 'ai-1', target: 'end-normal-1', sourceHandle: 'positive' },
      { id: 'e5', source: 'escalate-1', target: 'notify-1' },
      { id: 'e6', source: 'notify-1', target: 'track-escalation-1' },
      { id: 'e7', source: 'track-escalation-1', target: 'end-escalated-1' },
    ],
  },
];

export default aiPoweredWorkflowTemplates;

